route:
# `group_wait` default is 30s, indicating the duration to hold off before sending an alert notification.
  group_wait: 5s
  receiver: webhook_receiver

receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/614c3637-bc6b-4a85-9873-89b8fcbe3fb8'
        send_resolved: false